# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Walden Pond
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://waldenpond.press" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

#manifest
short_name: "Walden Pond"
name: "Walden Pond"
default_locale: "en"
start_url: "/?utm_source=homescreen"
manifest_description: "A little break to read in peace"
background_color: "#FCFCFC"
theme_color: "#1f597a"
display: fullscreen
